spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/myblog"
    username: root
    password: master22
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
app:
  jwt-secret:
    daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 904800000